# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: NodeTool@0
      displayName: 'Use Node version'
      inputs:
        versionSpec: 10.14

    - task: Npm@0
      displayName: 'npm install'
      inputs:
        arguments: '--force'

    - task: ArchiveFiles@1
      displayName: 'Archive files '
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false

    - task: CopyFiles@2
      displayName: 'Copy File to: $(TargetFolder)'
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '$(Build.BuildId).zip'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: NodeTool@0
      displayName: 'Use Node version'
      inputs:
        versionSpec: 10.14

    - task: Npm@0
      displayName: 'npm install'
      inputs:
        arguments: '--force'
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    
